### ISSUE TITLE
64bit version has released!

### ISSUE THREAD

**Issue by mashizora** [tyrone-sudeium/LaunchXIV#2]
FFXIV 64bit macOS version has released, but the new launcher is running by wine. So I am looking for a better launcher. Does LaunchXIV fits 64bit version client?

**Comment by tyrone-sudeium** [comment]
It definitely does not, as of right now. I will fix it, in time, however I've got some problems with my development computer, which I updated to the macOS Beta version. Seems like FINAL FANTASY XIV just doesn't work at all in that version, the `ffxivboot` update fails every time.

It might take me a while to update LaunchXIV because of this, since I'll need to install Mojave again on another partition...

**Comment by mashizora** [comment]
FFXIV 64bit release works really well in Mojave expect for its ridiculous launcher. However, your repo provided a meaningful idea.
